name: Build Windows Server 2019

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Download eCAL
      uses: i3h/download-release-asset@v1.3.2
      with:
        owner: continental
        repo: ecal
        tag: latest
        file: ecal_5.9.0-win64.exe
#        path: # optional
#        token: # optional    
