name: Build Windows Server 2019

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

#    steps:
#    - name: Install eCAL
#      run: |
#   https://github.com/continental/ecal/releases/download/v5.9.0/ecal_5.9.0-win64.exe
